// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbVKqDmVVGTYw4biKkCEy0XreRJJWZWPs',
    appId: '1:1064198264689:web:2445c83eaf7b929b18c8d0',
    messagingSenderId: '1064198264689',
    projectId: 'mu-app-d2579',
    authDomain: 'mu-app-d2579.firebaseapp.com',
    storageBucket: 'mu-app-d2579.firebasestorage.app',
    measurementId: 'G-9XCZ7HN64F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUblBdU_bF2BjjMxNOjtA1Uk9KGOuzGpE',
    appId: '1:1064198264689:android:c3a24c05f44befb918c8d0',
    messagingSenderId: '1064198264689',
    projectId: 'mu-app-d2579',
    storageBucket: 'mu-app-d2579.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATp1ULM9ovRpzHuLKnUqEyhBT0LE8QX7U',
    appId: '1:1064198264689:ios:f47862b0fd3cc78c18c8d0',
    messagingSenderId: '1064198264689',
    projectId: 'mu-app-d2579',
    storageBucket: 'mu-app-d2579.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATp1ULM9ovRpzHuLKnUqEyhBT0LE8QX7U',
    appId: '1:1064198264689:ios:f47862b0fd3cc78c18c8d0',
    messagingSenderId: '1064198264689',
    projectId: 'mu-app-d2579',
    storageBucket: 'mu-app-d2579.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbVKqDmVVGTYw4biKkCEy0XreRJJWZWPs',
    appId: '1:1064198264689:web:6e111aa7a247db0818c8d0',
    messagingSenderId: '1064198264689',
    projectId: 'mu-app-d2579',
    authDomain: 'mu-app-d2579.firebaseapp.com',
    storageBucket: 'mu-app-d2579.firebasestorage.app',
    measurementId: 'G-NESRCPV7L0',
  );

}